graph LR
subgraph Artificial Intelligence (AI)
    subgraph Machine Learning (ML)
        subgraph Deep Learning (DL)
            subgraph Generative AI
            end
        end
        subgraph Reinforcement Learning (RL)
            %% nothing to see here
        end
    end
end
