graph LR
  subgraph AI [Artificial Intelligence (AI)]
    subgraph ML [Machine Learning (ML)]
      subgraph DL [Deep Learning (DL)]
        subgraph GenerativeAI [Generative AI]
        end
      end
      subgraph RL [Reinforcement Learning (RL)]
      end
    end
  end
