graph LR
  subgraph AI
    subgraph ML
      subgraph DL
        GenerativeAI
      end
    end
    subgraph RL
    end
  end


%%  subgraph AI [Artificial Intelligence (AI)]
%%    subgraph ML [Machine Learning (ML)]
%%      subgraph DL [Deep Learning (DL)]
%%        subgraph GenerativeAI [Generative AI]
%%      subgraph RL [Reinforcement Learning (RL)]
