gantt
    title Evolution of AI
    dateFormat YYYY
    axisFormat %Y

    section Milestones
    "Turing Test" :done, 1950, 1y
    "AI Coined" :done, 1956, 1y
    "ELIZA" :done, 1965, 1y
    "Stanford Cart" :done, 1979, 1y
    "Backpropagation" :done, 1986, 1y
    "Deep Blue" :done, 1997, 1y
    "Deep Belief Nets" :done, 2006, 1y
    "ImageNet" :done, 2009, 1y
    "AlexNet" :done, 2012, 1y
    "AlphaGo" :done, 2014, 1y
    "Tesla Autopilot" :done, 2015, 1y
    "AlphaGo Zero" :done, 2017, 1y
    "Transformer Model" :done, 2017, 1y
    "GPT-1" :done, 2018, 1y
    "GPT-3" :done, 2020, 1y
    "DALL-E and CLIP" :done, 2020, 1y
    "AlphaFold" :done, 2020, 1y
    "Tesla FSD Beta" :done, 2020, 1y
    "Codex" :done, 2021, 1y
    "Megatron-Turing NLG" :done, 2021, 1y
    "AlphaFold Recognition" :done, 2021, 1y
    "ChatGPT Release" :done, 2022, 1y
    "ChatGPT User Milestone" :done, 2023, 1y
